### ISSUE TITLE
What is "encoder.json" and "vocab.bpe"  when I'm running "create_data.ipynb" ?

### ISSUE THREAD

**Issue by zongshuai818** [ecchochan/roberta-tpu#8]
**1.** Before I run the Experiment 1 , should I run "create_data.ipynb"  first？

**2.** This error occurred while I was running "create_data.ipynb" ：
`Traceback (most recent call last):
  File "create_data.py", line 24, in <module>
    tk = tokenizer =  get_tokenizer()
  File "create_data.py", line 22, in <lambda>
    get_tokenizer = lambda: RobertaTokenizer(config_dir='roberta.large')
  File "roberta.pyx", line 601, in roberta.RobertaTokenizer.__init__
  File "roberta.pyx", line 229, in roberta.RobertaEncoder.__init__
  File "roberta.pyx", line 183, in roberta.get_encoder
FileNotFoundError: [Errno 2] No such file or directory: 'roberta.large/encoder.json'`

**So what is "encoder.json"**

Thank you for your help ！

**Comment by Winggi** [comment]
I am encountering the same error. Have you solved it?
